apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: NodePort
  selector:
     app.kubernetes.io/instance: k8ssandra-kube-prometheus-prometheus 
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9090
      targetPort: web
      protocol: TCP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
